language: haskell

ghc:
  - 7.8

install:
  - sudo apt-get update
  - sudo apt-get install libjpeg8-dev libpng12-dev catch liblapack-dev liblapack3 libblas-dev libblas3
  - cabal update
  - cabal install -j --only-dep  --enable-tests --force-reinstalls

script:
  - cabal configure --enable-tests && cabal build && cabal test

